<a href="https://colab.research.google.com/github/lokeshneerasa/Pandas/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#---------------------------------> PANDAS <----------------------------------#
##------------>1.SERIES <---------##
#1.EMPTY SERIES OBJECT
import pandas as pd
a=pd.Series()
print(a)
print(type(a))

Series([], dtype: object)
<class 'pandas.core.series.Series'>


In [ ]:
#2.CREATING SERIES BY USING LIST
import pandas as pd
a=[85,93,52,66,30]
b=pd.Series(a)
print(b)


0    85
1    93
2    52
3    66
4    30
dtype: int64


In [ ]:
#CREATING SERIES BY USING LIST,ASSIGNING A NAME
import pandas as pd
a=[62,89,45,23,93]
b=pd.Series(a,name="Marks")
print(b)


0    62
1    89
2    45
3    23
4    93
Name: Marks, dtype: int64


In [ ]:
import pandas as pd
a=pd.Series([10,20,30,40,50])
print(a)



0    10
1    20
2    30
3    40
4    50
dtype: int64


In [ ]:
import pandas as pd
a=pd.Series([10,20,30,40],name="RoLLNO")
print(a)

0    10
1    20
2    30
3    40
Name: RoLLNO, dtype: int64


In [ ]:
import pandas as pd
a=pd.Series(["LOKI","MOHAN","GANI","VAMSI"],name="Students")
print(a)

0     LOKI
1    MOHAN
2     GANI
3    VAMSI
Name: Students, dtype: object


In [ ]:
#CREATING SERIES OBJECT BY USING RANGE AND LIST
import pandas as pd
a=range(100)
b=list(a)
c=pd.Series(a)
print(c)

0      0
1      1
2      2
3      3
4      4
      ..
95    95
96    96
97    97
98    98
99    99
Length: 100, dtype: int64


In [ ]:
#3.CREATING A SERIES FROM A ARRAY
import pandas as pd
import numpy as np
a=[10,20,30,40,50]
b=np.array(a)
print(b)
print(type(b))


[10 20 30 40 50]
<class 'numpy.ndarray'>


In [ ]:
#FINDING DATATYPE OF AN ARRAY
import pandas as pd
import numpy as np
a=(10,20,30,40,50)
b=np.array(a)
r=list(a)
print(b)
print(type(a))

[10 20 30 40 50]
<class 'tuple'>


In [ ]:
#creating ndarray and passing argument to the Series
import pandas as pd
import numpy as np
a=[10,20,30,40,50]
b=np.array(a)
c=pd.Series(b)
print(c)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [ ]:
#Creating Series using ndarray
##Ex1:
import pandas as pd
import numpy as np
values=['a','b','c','d']
data=np.array(values)
s=pd.Series(data)
print(s)

0    a
1    b
2    c
3    d
dtype: object


In [ ]:
##Ex2:
import pandas as pd
import numpy as np
values=["loki","mohan","dimple","murari"]
data=np.array(values)
s=pd.Series(data)
print(s)


0      loki
1     mohan
2    dimple
3    murari
dtype: object


In [ ]:
#----------------INDEX IN SERIES----------------------#
#Creating Series object and giving name and index
##Ex1:
import pandas as pd
a=[156,123,86,62,76]
i=[10,20,30,40,50]
b=pd.Series(a,name="Marks",index=i)
print(b)


10    156
20    123
30     86
40     62
50     76
Name: Marks, dtype: int64


In [ ]:
#Ex2:
import pandas as pd
Prices=[50000,75000,90000,120000]
Products=["Lenovo","Dell","Honor","MacBook"]
b=pd.Series(Prices,name="Laptops",index=Products)
print(b)


Lenovo      50000
Dell        75000
Honor       90000
MacBook    120000
Name: Laptops, dtype: int64


In [ ]:
##Ex3:
import pandas as pd
sales=pd.Series([2000,6000,4500,7100,3600],index=["jan","feb","mar","apr","may"])
print(sales)

jan    2000
feb    6000
mar    4500
apr    7100
may    3600
dtype: int64


In [ ]:
#-----Accessing values in Series------#
##Ex:1
import pandas as pd
a=[45,61,85,33,54]
b=pd.Series(a,name="Marks")
print(b)
print()
print(b[0])
print(b[1])


0    45
1    61
2    85
3    33
4    54
Name: Marks, dtype: int64

45
61


In [ ]:
##Ex:2
import pandas as pd
Prices=[50000,75000,90000,120000]
Products=["Lenovo","Dell","Honor","MacBook"]
b=pd.Series(Prices,name="Laptops",index=Products)
print(b)
print()
print(b["Lenovo"])
print(b["MacBook"])




Lenovo      50000
Dell        75000
Honor       90000
MacBook    120000
Name: Laptops, dtype: int64

50000
120000


In [ ]:
###---Finding values in Dictionary using Series----####
#Ex:1
import pandas as pd
emp_data={"idno":250,"name":"loki","salary":25000.00}
s=pd.Series(emp_data)
print(s.iloc[0])
print(s.iloc[1])
print(s.iloc[2])


250
loki
25000.0


In [ ]:
#Ex2:Key not Available Sometimes
import pandas as pd
emp_data={"idno":250,"name":"loki","salary":25000.00}
s=pd.Series(emp_data)
data=s.get(["deptno"],"Not a key")
print(data)


Not a key


In [ ]:
##---- Getting Top Rows using Series ------##
import pandas as pd
emp_data={"name":"lokesh","age":22,"job":"data scientist"}
s=pd.Series(emp_data)
print(s.head(2))


name    lokesh
age         22
dtype: object


In [ ]:
##------Getting The Bottom Rows Using Series-------##
import pandas as pd
student_data={"name":"lokesh","class":12,"RollNo":33,"Branch":"MPC"}
s=pd.Series(student_data)
print(s.tail(3))


class      12
RollNo     33
Branch    MPC
dtype: object


In [ ]:
##---------NaN Using in Series--------------##
import pandas as pd
sales=pd.Series([100,np.nan,300,400,500],index=["jan","feb","march","april","march"],name="data")
print(sales)
print(sales.hasnans)
print(sales.ndim)
print(sales.shape)


jan      100.0
feb        NaN
march    300.0
april    400.0
march    500.0
Name: data, dtype: float64
True
1
(5,)


In [ ]:
##---------NaN Using in Series--------------##
#Ex:1 Creating Series using with NaN valus
import pandas as pd
import numpy as np
marks=[89,45,23,np.nan,78,np.nan,45]
a=pd.Series(marks)
print(a)

0    89.0
1    45.0
2    23.0
3     NaN
4    78.0
5     NaN
6    45.0
dtype: float64


In [ ]:
#Ex:2
import pandas as pd
import numpy as np
names=["Loki","Mohan",np.nan,"Ganesh","Murari"]
a=pd.Series(names)
print(a)

0      Loki
1     Mohan
2       NaN
3    Ganesh
4    Murari
dtype: object


In [ ]:
#-----------------------4. PANDAS – SERIES - ATTRIBUTES ------------------------#
##1.Values
#Ex:1
import pandas as pd
import numpy as np
marks=[46,78,52,63,36]
a=pd.Series(marks)
print(a)
print(a.values)


0    46
1    78
2    52
3    63
4    36
dtype: int64
[46 78 52 63 36]


In [ ]:
#Ex:2
import pandas as pd
import numpy as np
names=["Loki","Mohan","Gani","Murari"]
a=pd.Series(names)
print(a)
print(a.values)

0      Loki
1     Mohan
2      Gani
3    Murari
dtype: object
['Loki' 'Mohan' 'Gani' 'Murari']


In [ ]:
#Ex:3
import pandas as pd
import numpy as np
prices=[95.4,782.4,451.2,585.4]
a=pd.Series(prices)
print(a)
print(a.values)

0     95.4
1    782.4
2    451.2
3    585.4
dtype: float64
[ 95.4 782.4 451.2 585.4]


In [ ]:
##2.INDEX
#EX:1
import pandas as pd
import numpy as np
scores=[24,31,15,27,19]
a=pd.Series(scores)
print(a)
print(a.index)

0    24
1    31
2    15
3    27
4    19
dtype: int64
RangeIndex(start=0, stop=5, step=1)


In [ ]:
#EX:2
import pandas as pd
import numpy as np
scores=[24,31,15,27,19]
i=[1,2,3,4,5]
a=pd.Series(scores,index=i)
print(a)
print(a.index)



1    24
2    31
3    15
4    27
5    19
dtype: int64
Index([1, 2, 3, 4, 5], dtype='int64')


In [ ]:
#EX:3
import pandas as pd
import numpy as np
rates=[52.3,86,78,45,12]
i=[1,2,3,4,5]
a=pd.Series(rates,index=i)
print(a)
print(a.index)


1    52.3
2    86.0
3    78.0
4    45.0
5    12.0
dtype: float64
Index([1, 2, 3, 4, 5], dtype='int64')


In [ ]:
#EX:4
import pandas as pd
import numpy as np
names=["Loki","Mohan","Gani","Murari"]
index=[31,32,33,34]
a=pd.Series(names,index=index)
print(a)
print(a.index)

31      Loki
32     Mohan
33      Gani
34    Murari
dtype: object
Index([31, 32, 33, 34], dtype='int64')


In [ ]:
#EX:5
import pandas as pd
import numpy as np
values=[10,20,30,40,50,60,70,80]
index=pd.RangeIndex(start=0,stop=16,step=2)
a=pd.Series(values,index=index)
print(a)
print(a.index)




0     10
2     20
4     30
6     40
8     50
10    60
12    70
14    80
dtype: int64
RangeIndex(start=0, stop=16, step=2)


In [ ]:
##3.DTYPES(DATATYPES)
#EX:1
import pandas as pd
import numpy as np
scores=[47,51,75,63,83,60]
a=pd.Series(scores)
print(a)
print(a.dtype)

0    47
1    51
2    75
3    63
4    83
5    60
dtype: int64
int64


In [ ]:
#EX:2
import pandas as pd
import numpy as np
rates=[54.7,64.8,85.4,76.2,45.7]
a=pd.Series(rates)
print(a)
print(a.dtype)

0    54.7
1    64.8
2    85.4
3    76.2
4    45.7
dtype: float64
float64


In [ ]:
#EX:3
import pandas as pd
import numpy as np
employees=["Lokesh","Mohan","Murari","Gani"]
a=pd.Series(employees)
print(a)
print(a.dtype)

0    Lokesh
1     Mohan
2    Murari
3      Gani
dtype: object
object


In [ ]:
##4.SIZE
#EX:1
import pandas as pd
import numpy as np
marks=[73,59,31,25,13,40,70]
a=pd.Series(marks)
print(a)
print(a.size)

0    73
1    59
2    31
3    25
4    13
5    40
6    70
dtype: int64
7


In [ ]:
#EX:2
import pandas as pd
import numpy as np
names=["Lokesh","Tarun","Babi","Nani"]
a=pd.Series(names)
print(a)
print(a.size)

0    Lokesh
1     Tarun
2      Babi
3      Nani
dtype: object
4


In [ ]:
#----------------------5.PANDAS- Series- Methods-------------------#
#1.head()
import pandas as pd
import numpy as np
scores=[28,53,90,23,57,16]
a=pd.Series(scores)
print(a)
print()
print(a.head())
print()
print(a.head(3))


0    28
1    53
2    90
3    23
4    57
5    16
dtype: int64

0    28
1    53
2    90
3    23
4    57
dtype: int64

0    28
1    53
2    90
dtype: int64


In [ ]:
##2.tail()
import pandas as pd
import numpy as np
scores=[28,53,90,23,57,16]
a=pd.Series(scores)
print(a)
print()
print(a.tail())
print()
print(a.tail(4))

0    28
1    53
2    90
3    23
4    57
5    16
dtype: int64

1    53
2    90
3    23
4    57
5    16
dtype: int64

2    90
3    23
4    57
5    16
dtype: int64


In [ ]:
##3.SUM()
#EX:1
import pandas as pd
import numpy as np
scores=[28,53,90,23,57,16]
a=pd.Series(scores)
print(a)
print()
print(a.sum())

0    28
1    53
2    90
3    23
4    57
5    16
dtype: int64

267


In [ ]:
#EX:2
import pandas as pd
import numpy as np
scores=[42,75,np.nan,23,45,np.nan,43]
a=pd.Series(scores)
print(a)
print()
print(a.sum())

0    42.0
1    75.0
2     NaN
3    23.0
4    45.0
5     NaN
6    43.0
dtype: float64

228.0


In [ ]:
##4.COUNT()
import pandas as pd
import numpy as np
scores=[28,53,90,23,57,16,19]
a=pd.Series(scores)
print(a)
print(a.count())

0    28
1    53
2    90
3    23
4    57
5    16
6    19
dtype: int64
7


In [ ]:
##5.MEAN()
import pandas as pd
import numpy as np
scores=[28,53,90,23,57,16,19]
a=pd.Series(scores)
print(a)
print()
print(a.mean())

0    28
1    53
2    90
3    23
4    57
5    16
6    19
dtype: int64

40.857142857142854


In [ ]:
#MEDIAN
import pandas as pd
import numpy as np
scores=[10,25,37,45,56]
a=pd.Series(scores)
print(a)
print()
print(a.median())


0    10
1    25
2    37
3    45
4    56
dtype: int64

37.0


In [ ]:
#MODE
import pandas as pd
import numpy as np
scores=[10,20,30,40,20,50,20]
a=pd.Series(scores)
print(a)
print()
print(a.mode())

0    10
1    20
2    30
3    40
4    20
5    50
6    20
dtype: int64

0    20
dtype: int64


In [ ]:
##6.DESCRIBE()
import pandas as pd
import numpy as np
scores=[10,20,30,40,50]
a=pd.Series(scores)
print(a)
print()
print(a.describe())

0    10
1    20
2    30
3    40
4    50
dtype: int64

count     5.000000
mean     30.000000
std      15.811388
min      10.000000
25%      20.000000
50%      30.000000
75%      40.000000
max      50.000000
dtype: float64


In [ ]:
##7.UNIQUE()
import pandas as pd
import numpy as np
scores=[12,25,17,12,27,12,20]
a=pd.Series(scores)
print(a)
print()
print(a.unique())

0    12
1    25
2    17
3    12
4    27
5    12
6    20
dtype: int64

[12 25 17 27 20]


In [ ]:
##8.nunique
import pandas as pd
import numpy as np
scores=[12,25,17,12,27,12,20]
a=pd.Series(scores)
print(a)
print()
print(a.nunique())



0    12
1    25
2    17
3    12
4    27
5    12
6    20
dtype: int64

5


In [1]:
###################################  PANDAS-2.DATAFRAMES ############################################
#1. Creating an Empty DataFrame
import pandas as pd
df=pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [4]:
#2. Create a DataFrame by using list
#EX:1
import pandas as pd
marks=[78,45,62,97,24,51]
df=pd.DataFrame(marks)
print(df)


    0
0  78
1  45
2  62
3  97
4  24
5  51


In [5]:
#EX:2
import pandas as pd
data=[78,45,62,97,24,51]
df=pd.DataFrame(data,columns=["Marks"])
print(df)

   Marks
0     78
1     45
2     62
3     97
4     24
5     51


In [6]:
#3.Creating a DataFrame from a List of Lists
import pandas as pd
data=[
    ['loki',23,96],
    ['mohan',22,89],
    ['dimple',20,87],
    ['murari',21,91]
]
df=pd.DataFrame(data,columns=["Name","Age","Marks"])
print(df)

     Name  Age  Marks
0    loki   23     96
1   mohan   22     89
2  dimple   20     87
3  murari   21     91


In [ ]:
#4.Creating a DataFrame from a Dictionary
import pandas as pd
data={
     'Name':['loki','mohan','dimple','murari'],
     'Age':[23,22,20,21],
     'Marks':[96,89,87,91]
}
df=pd.DataFrame(data)
print(df)

     Name  Age  Marks
0    loki   23     96
1   mohan   22     89
2  dimple   20     87
3  murari   21     91


In [16]:
#5.Import csv file using Pandas
from google.colab import files
uploaded = files.upload()
import pandas as pd
df=pd.read_csv("Company Sales Data 2020.csv")
print(df)

Saving Company Sales Data 2020.csv to Company Sales Data 2020 (2).csv
       OrderDate   StockDate OrderNumber  ProductKey  CustomerKey  \
0     2020-01-01  2019-09-21     SO45080         332        14657   
1     2020-01-01  2019-12-05     SO45079         312        29255   
2     2020-01-01  2019-10-29     SO45082         350        11455   
3     2020-01-01  2019-11-16     SO45081         338        26782   
4     2020-01-02  2019-12-15     SO45083         312        14947   
...          ...         ...         ...         ...          ...   
2625  2020-12-31  2020-11-29     SO48728         354        13111   
2626  2020-12-31  2020-11-14     SO48729         324        26563   
2627  2020-12-31  2020-12-02     SO48724         340        20722   
2628  2020-12-31  2020-10-09     SO48723         369        14944   
2629  2020-12-31  2020-11-22     SO48726         383        24915   

      TerritoryKey  OrderLineItem  OrderQuantity  
0                1              1              1  

In [20]:
#6.Import Excel Files using pandas
from google.colab import files
uploaded=files.upload()

import pandas as pd
data=pd.read_excel("emp monthly sal.xlsx")
print(data)

Saving emp monthly sal.xlsx to emp monthly sal (1).xlsx
   npdays=31 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0        Eid      Ename  Basic Sal         Ta         DA        HRA   
1        101     Vishnu      30000       2400       3000       2700   
2        102     Ganesh      20000       1600       2000       1800   
3        103     Sanjay      25000       2000       2500       2250   
4        104     Kalyan      40000       3200       4000       3600   
5        105     Vishnu      32000       2560       3200       2880   
6        106     Ganesh      28000       2240       2800       2520   
7        107     Sanjay      33000       2640       3300       2970   
8        108     Kalyan      29000       2320       2900       2610   
9        109     Sanjay      67000       5360       6700       6030   
10       110       Ajay      65000       5200       6500       5850   
11       111     Kalyan      41000       3280       4100       3690   
12       112     Kaly